# Generated by Django 4.2 on 2023-05-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_product_brand_product_category_product_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
