# Generated by Django 4.2 on 2023-05-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_rename_is_acitve_client_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
