# Generated by Django 4.2 on 2023-05-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='nums_rating',
            field=models.IntegerField(default=0),
        ),
    ]
