# Generated by Django 4.2 on 2023-05-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_alter_review_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='visa/card', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
