# Generated by Django 4.2 on 2023-05-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
