# Generated by Django 4.2 on 2023-05-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_client_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_acitve',
            field=models.BooleanField(default=False),
        ),
    ]
