# Generated by Django 4.2 on 2023-05-03 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_client_is_acitve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='is_acitve',
            new_name='is_active',
        ),
    ]
