# Generated by Django 4.2 on 2023-05-03 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0016_rename_nums_reviews_product_num_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='Users.product'),
        ),
    ]
