# Generated by Django 4.2 on 2023-05-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_alter_order_shipping_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order_item',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='order',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='Users.order'),
        ),
    ]
